stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile-Rancher
      buildContext: .
      tag: drengir/narf2
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
