stages:
- name: build
  steps:
  - runScriptConfig:
      image: multiarch/qemu-user-static:register
      shellScript: date
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: drengir/narf2
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
